### PR TITLE
🐛 fix: support delete/update for out-of-line keys

### LINKED ISSUE #41: Error deleting records
When i try and delete an IndexedDB entry I get the following error in your plugins error console:
```
Error deleting records
Failed to execute 'delete' on 'IDBObjectStore': No key or key range specified. DataError: Failed to execute 'delete' on 'IDBObjectStore': No key or key range specified.
```

Image

Love the extension, would love to be able to delete records.  Thanks!

### PR DESCRIPTION
**Pull request by adityashirsatrao007**
## Description
Fixes #41

This PR addresses an issue where deleting or updating records failed for object stores with out-of-line keys (e.g., `autoIncrement` stores without a defined `keyPath` in the object). In such cases, the primary key was missing from the records loaded into the UI, resulting in a "No key or key range specified" error.

## Changes
- **`src/databases/indexedDb/loadRecords.ts`**: Updated logic to detect out-of-line keys (`keyPath === null`). The loader now explicitly fetches primary keys using `.each()` and injects them into the record objects as an `id` property.
- **`src/databases/indexedDb/indexedDbOps.ts`**: Updated `deleteRecords` and `updateRecord` to use the injected `id` property as a fallback for key resolution when the table's `keyPath` is null.

## Verification
- Validated using a custom reproduction script with `fake-indexeddb` which simulated the failure condition.
- Verified that records with out-of-line keys can now be successfully deleted.

### CODE REVIEW

**Comment by haroonwaves** [comment]
Thanks for the PR. I’ll merge it once it’s tested

File: src/databases/indexedDb/indexedDbOps.ts [hunk 1]
```diff
@@ -21,11 +21,14 @@ async function updateRecord(existingRow: object, updatedRow: object) {
...
-	const primaryKey = Array.isArray(selectedTable.schema.primKey.keyPath)
-		? (selectedTable.schema.primKey.keyPath[0] as string)
-		: (selectedTable.schema.primKey.keyPath as string);
+	const primKeyPath = selectedTable.schema.primKey.keyPath;
+	const primaryKey = Array.isArray(primKeyPath)
+		? (primKeyPath[0] as string)
+		: (primKeyPath as string);
 
-	const primaryValue = existingRow[primaryKey as keyof typeof existingRow];
+	const keyField = primaryKey || 'id';
```
Comment (haroonwaves) [inline src/databases/indexedDb/indexedDbOps.ts]: We already store `cursor.primaryKey` in the `__primaryKey__` property inside loadRecords.
To get that right, replace usages of `id` with `__primaryKey__`.

```suggestion
	const keyField = primaryKey?.trim() || '__primaryKey__';
```

File: src/databases/indexedDb/indexedDbOps.ts [hunk 2]
```diff
@@ -21,11 +21,14 @@ async function updateRecord(existingRow: object, updatedRow: object) {
 
 	if (!selectedTable) return;
 
-	const primaryKey = Array.isArray(selectedTable.schema.primKey.keyPath)
-		? (selectedTable.schema.primKey.keyPath[0] as string)
-		: (selectedTable.schema.primKey.keyPath as string);
+	const primKeyPath = selectedTable.schema.primKey.keyPath;
+	const primaryKey = Array.isArray(primKeyPath)
+		? (primKeyPath[0] as string)
+		: (primKeyPath as string);
```
Comment (haroonwaves) [inline src/databases/indexedDb/indexedDbOps.ts]: Please remove the type assertion here, as `primaryKey` can legitimately be either a `string` or `undefined`.

```suggestion
	const primaryKey = Array.isArray(primKeyPath)
		? (primKeyPath[0])
		: (primKeyPath);
```

File: src/databases/indexedDb/indexedDbOps.ts [hunk 3]
```diff
@@ -38,14 +41,17 @@ async function deleteRecords() {
...
```
Comment (haroonwaves) [inline src/databases/indexedDb/indexedDbOps.ts]: Please remove the type assertion here, as `primaryKey` can legitimately be either a `string` or `undefined`.

```suggestion
	const primaryKey = Array.isArray(primKeyPath)
		? (primKeyPath[0])
		: (primKeyPath);
```

File: src/databases/indexedDb/indexedDbOps.ts [hunk 4]
```diff
@@ -38,14 +41,17 @@ async function deleteRecords() {
...
+
+	const keyField = primaryKey || 'id';
```
Comment (haroonwaves) [inline src/databases/indexedDb/indexedDbOps.ts]: We already store `cursor.primaryKey` in the `__primaryKey__` property inside loadRecords.
To get that right, replace usages of `id` with `__primaryKey__`.

```suggestion
	const keyField = primaryKey?.trim() || '__primaryKey__';
```

File: src/databases/indexedDb/loadRecords.ts [hunk 5]
```diff
@@ -133,6 +133,28 @@ export async function loadRecords(countUpdater: ((totalCount: number) => void) |
 		return items.slice(start, end);
 	}
 
+	// Handle out-of-line keys (auto-increment with no key path)
+	const primKeySchema = table.schema.primKey;
+	const keyPath = primKeySchema.keyPath;
+	const isOutOfLineKey = (keyPath as string | string[] | null) === null;
```
Comment (haroonwaves) [inline src/databases/indexedDb/loadRecords.ts]: Please update this logic to correctly detect an `outOfLineKey`.

keyPath can be a `string`, `string[]`, or `undefined`, and trimming adds extra safety since some values may contain only whitespace.

```suggestion
	const primKeyPath = table.schema.primKey.keyPath;
	const primaryKey = Array.isArray(primKeyPath)
		? (primKeyPath[0])
		: (primKeyPath);

	const hasOutOfLineKeys = !primaryKey?.trim();
```

File: src/databases/indexedDb/loadRecords.ts [hunk 6]
```diff
@@ -133,6 +133,28 @@ export async function loadRecords(countUpdater: ((totalCount: number) => void) |
...
+			.offset(pageIndex * pageSize)
+			.limit(pageSize)
+			.each((item, cursor) => {
+				items.push(item);
+				keys.push(cursor.primaryKey);
+			});
+
+		return items.map((item, index) => {
+			return { ...item, __primaryKey__: keys[index] };
+		});
```
Comment (haroonwaves) [inline src/databases/indexedDb/loadRecords.ts]: This change looks promising since it removes the extra loop at the end.

I’d like to test this approach, as attaching `cursor.primaryKey` during iteration should be more efficient and simpler.

```suggestion
		const items: any[] = [];

		await processedCollection
			.offset(pageIndex * pageSize)
			.limit(pageSize)
			.each((item, cursor) => {
				items.push({...item, __primaryKey__: cursor.primaryKey});
			});

		return items;
```

**Review by haroonwaves — CHANGES_REQUESTED** [review]

**Comment by haroonwaves** [comment]
Additionally, in `loadRecords` the sort uses different return flow so the handling of out-of-line-key have no effect when user used any sorted field on the table.

I would request you to test the below for the sort flow. hope it can handle the case when user try to delete/modify data while sort is enabled.


```
	if (needsMemorySort && sort) {
		// Check if we need to handle out-of-line keys
		if (hasOutOfLineKeys) {
			// Capture both items and their primary keys
			const itemsWithKeys: Array<{ item: any; __primaryKey__: any }> = [];

			await processedCollection.each((item, cursor) => {
				itemsWithKeys.push({ item, __primaryKey__: cursor.primaryKey });
			});

			// Sort in memory
			itemsWithKeys.sort((a, b) => {
				const aValue = a.item[sort.id];
				const bValue = b.item[sort.id];

				if (aValue === bValue) return 0;
				if (aValue == null) return 1;
				if (bValue == null) return -1;

				const comparison = aValue < bValue ? -1 : 1;
				return sort.desc ? -comparison : comparison;
			});

			// Paginate
			const start = pageIndex * pageSize;
			const end = Math.min(itemsWithKeys.length, start + pageSize);

			return itemsWithKeys.slice(start, end);
		} else {
			// In-line keys - use Dexie's sortBy
			let items: object[];

			if (sort.desc) processedCollection = processedCollection.reverse();
			items = await processedCollection.sortBy(sort.id);

			const start = pageIndex * pageSize;
			const end = Math.min(items.length, start + pageSize);

			return items.slice(start, end);
		}
	}
```

**Comment by adityashirsatrao007** [comment]
Greetings, fellow traveler of the binary streams.

I have synchronized these changes with the latest currents of the main branch and resolved the conflicts that manifested. The logic has been fortified to robustly handle `out-of-line` keys, ensuring that order is preserved even when `keyPath` is absent from the schema.

The build rituals (typechecks, linting, and compilation) have been performed and passed on my local machine. The code is ready for your inspection.

May your queries be optimized and your indexes covered.

File: src/databases/indexedDb/loadRecords.ts [hunk 7]
```diff
@@ -121,16 +121,67 @@ export async function loadRecords(countUpdater: ((totalCount: number) => void) |
...
 
-	if (needsMemorySort && sort) {
-		let items: object[];
-
-		if (sort.desc) processedCollection = processedCollection.reverse();
-		items = await processedCollection.sortBy(sort.id);
+	// Determine if there are out-of-line keys
+	const primKeySchema = table.schema.primKey;
+	const keyPath = primKeySchema.keyPath;
+	const isOutboundKey = (keyPath as string | string[] | null) === null;
```
Comment (haroonwaves) [inline src/databases/indexedDb/loadRecords.ts]: I think this condition got accidentally modified when you fix conflict

```suggestion
	const primKeyPath = table.schema.primKey.keyPath;
	const primaryKey = Array.isArray(primKeyPath)
		? (primKeyPath[0])
		: (primKeyPath);
	const hasOutOfLineKeys = !primaryKey?.trim();
```

File: src/databases/indexedDb/loadRecords.ts [hunk 8]
```diff
@@ -121,16 +121,67 @@ export async function loadRecords(countUpdater: ((totalCount: number) => void) |
...
 
-		const start = pageIndex * pageSize;
-		const end = Math.min(items.length, start + pageSize);
+	if (needsMemorySort && sort) {
+		// Check if we need to handle out-of-line keys
+		if (isOutboundKey) {
```
Comment (haroonwaves) [inline src/databases/indexedDb/loadRecords.ts]: We have renamed this `const`.

```suggestion
		if (hasOutOfLineKeys) {
```

File: src/databases/indexedDb/loadRecords.ts [hunk 9]
```diff
@@ -121,16 +121,67 @@ export async function loadRecords(countUpdater: ((totalCount: number) => void) |
...
+
+			const start = pageIndex * pageSize;
+			const end = Math.min(items.length, start + pageSize);
+
+			return items.slice(start, end);
+		}
+	}
 
-		return items.slice(start, end);
+	if (isOutboundKey) {
```
Comment (haroonwaves) [inline src/databases/indexedDb/loadRecords.ts]: We have renamed this `const`.

```suggestion
	if (hasOutOfLineKeys) {
```

File: src/databases/indexedDb/loadRecords.ts [hunk 10]
```diff
@@ -121,16 +121,67 @@ export async function loadRecords(countUpdater: ((totalCount: number) => void) |
...
+			.offset(pageIndex * pageSize)
+			.limit(pageSize)
+			.each((item, cursor) => {
+				items.push(item);
+				keys.push(cursor.primaryKey);
+			});
+
+		return items.map((item, index) => {
+			return { ...item, id: keys[index] };
+		});
```
Comment (haroonwaves) [inline src/databases/indexedDb/loadRecords.ts]: I think this improvement got accidentally modified when you fix conflict.

```suggestion
		const items: any[] = [];

		await processedCollection
			.offset(pageIndex * pageSize)
			.limit(pageSize)
			.each((item, cursor) => {
				items.push({...item, __primaryKey__: cursor.primaryKey});
			});
	
		return items;
```

**Review by haroonwaves — CHANGES_REQUESTED** [review]
